# Discovery api playbook
---

- name: create Discovery api AMI
  hosts: localhost
  gather_facts: false
  tasks:
  - name: load variables
    ansible.builtin.include_vars:
      file: "{{ ansible_var_file }}"

  - name: switch role credentials
    community.aws.sts_assume_role:
      role_arn: "{{ lookup ('env', 'AWS_ROLE_ARN') }}"
      role_session_name: "s-devops"
    register: assumed_role

  # ----------------------------------------------------------------------------
  # The base AMI has the EC2Launch version 2 installed by default
  # ----------------------------------------------------------------------------
  - name: get Windows 2019 Core AMI
    amazon.aws.ec2_ami_info:
      owners: amazon
      region: "{{ region }}"
      filters:
        name: "Windows_Server-2019-English-Core-Base*"
        #name: "EC2LaunchV2-Windows_Server-2019-English-Core-Base*"
    register: findami

  - name: set latest AMI
    set_fact:
      latest_ami: >
        {{ findami.images | sort(attribute='creation_date') | last }}

  - name: create security group - allowing updates and downloads
    amazon.aws.ec2_group:
      name: "ansible-ami-discovery-app-sg"
      description: "security group allowing updates and downloads"
      region: "{{ region }}"
      vpc_id: "{{ lookup( 'env', 'VPC_ID') }}"
      rules:
        - proto: "tcp"
          from_port: 1024
          to_port: 65535
          cidr_ip: "0.0.0.0/0"
          rule_desc: "for updates and downloads"
      rules_egress:
        - proto: "tcp"
          from_port: 80
          to_port: 80
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow updates and downloads"
        - proto: "tcp"
          from_port: 443
          to_port: 443
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow updates and downloads"
        - proto: "tcp"
          from_port: 1024
          to_port: 65535
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow replies"
      state: "present"
    register: ec2_sec_group

  - name: generate admin password
    set_fact:
      password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=24') }}"

# enable only for debugging purposes and never for live
#  - ansible.builtin.debug:
#      msg:
#        - "====================================================================="
#        - "{{ password }}"
#        - "====================================================================="

  - name: template userdata
    template:
      src: "./templates/userdata.ps1.j2"
      dest: "./userdata.ps1"
      force: yes

  - name: provisioning instance
    amazon.aws.ec2_instance:
      key_name: "{{ key_name }}"
      image_id: "{{ latest_ami.image_id }}"#
      instance_role: "discovery-ansible-ami-build-instance-role"
      instance_type: "t3a.large"
      metadata_options:
        http_endpoint: "enabled"
        http_tokens: "optional"
      name: "{{ service }}-app-wincore-primer-{{ env }}"
      network:
        assign_public_ip: yes
        delete_on_termination: yes
        subnet_id: "{{ lookup('env', 'SUBNET_ID') }}"
      region: "{{ region }}"
      security_groups: [ "{{ ec2_sec_group.group_id }}" ]
      state: "running"
      termination_protection: no
      user_data: "{{ lookup('file', './userdata.ps1') }}"
      wait: true
      wait_timeout: 500
      volumes:
        - device_name: "/dev/xvda"
          ebs:
            delete_on_termination: true
            encrypted: true
            volume_size: "{{ volume_size }}"
      vpc_subnet_id: "{{ lookup('env', 'SUBNET_ID') }}"
      tags:
        Environment: "{{ env }}"
        Service: "{{ service }}"
        Owner: "Digital Services"
        CreatedBy: "ansible"
        CostCentre: 53
        Terraform: false
    register: ec2

  - name: get instance ip address
    set_fact:
      instance_private_ip: "{{ ec2.instances[0].private_ip_address }}"
      instance_public_ip: "{{ ec2.instances[0].public_ip_address }}"
      instance_id: "{{ ec2.instances[0].instance_id }}"

  - ansible.builtin.debug:
      msg:
        - "====================================================================="
        - "instance started up"
        - "instance private ip: {{ instance_private_ip }}"
        - "instance id: {{ instance_id }}"
        - "instance public ip {{ instance_public_ip }}"
        - "====================================================================="

  - name: register new ec2 as host
    add_host:
      hostname: "{{ instance_public_ip }}:5986"
      groups: winhosts
      ansible_user: ansible-winrm
      ansible_password: "{{ password }}"
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_transport: basic
      ansible_winrm_message_encryption: auto
      ansible_winrm_server_cert_validation: ignore

  - name: wait for WinRM port
    ansible.builtin.wait_for:
      host: "{{ instance_public_ip }}"
      port: 5986
      delay: 120
      timeout: 600
      sleep: 10
      state: started
    register: port
    tags: [ ami ]

- name: switching hosts
  hosts: winhosts
  gather_facts: no
  connection: winrm
  port: 5986
  tasks:
  - ansible.builtin.debug:
      msg:
        - "====================================================================="
        - "checking userdata script has finished"
        - "20 second interval with max duration of 10 minutes"
        - "====================================================================="
  - name: check if userdata script has finished
    ansible.windows.win_stat:
      path: "C:\\finish-init.txt"
    register: init_finished
    until: init_finished.stat.exists
    retries: 30
    delay: 20

  - name: web-server || Web-Server,Web-WebServer
    ansible.windows.win_feature:
      name: Web-Server,Web-WebServer
    register: web_server

  - name: Common HTTP Features || Web-Default-Doc,Web-Dir-Browsing,Web-Http-Errors,Web-Static-Content,Web-Http-Redirect
    ansible.windows.win_feature:
      name: Web-Default-Doc,Web-Dir-Browsing,Web-Http-Errors,Web-Static-Content,Web-Http-Redirect
    register: web_common

  - name: Health and Diagnostics || Web-Http-Logging,Web-Request-Monitor,Web-Http-Tracing
    ansible.windows.win_feature:
      name: Web-Http-Logging,Web-Request-Monitor,Web-Http-Tracing
    register: web_health

  - name: Performance || Web-Stat-Compression
    ansible.windows.win_feature:
      name: Web-Stat-Compression
    register: web_performance

  - name: Security || Web-Filtering,Web-Basic-Auth,Web-Url-Auth,Web-Windows-Auth
    ansible.windows.win_feature:
      name: Web-Filtering,Web-Basic-Auth,Web-Url-Auth,Web-Windows-Auth
    register: web_security

  - name: Application Development || Web-Net-Ext,Web-Net-Ext45,Web-Asp-Net,Web-Asp-Net45,Web-ISAPI-Ext,Web-ISAPI-Filter,Web-WebSockets
    ansible.windows.win_feature:
      name: Web-Net-Ext,Web-Net-Ext45,Web-Asp-Net,Web-Asp-Net45,Web-ISAPI-Ext,Web-ISAPI-Filter,Web-WebSockets
    register: web_development

  - name: Management Tools || Web-Mgmt-Console,Web-Scripting-Tools,Web-Mgmt-Service
    ansible.windows.win_feature:
      name: Web-Mgmt-Console,Web-Scripting-Tools,Web-Mgmt-Service
    register: web_mgmt

  - name: .NET Framework 3.5 || NET-Framework-Core
    ansible.windows.win_feature:
      name: NET-Framework-Core
    register: web_frame35

  - name: .NET Framework 4.8 || NET-Framework-45-Core,NET-WCF-HTTP-Activation45,NET-WCF-TCP-PortSharing45
    ansible.windows.win_feature:
      name: NET-Framework-45-Core,NET-WCF-HTTP-Activation45,NET-WCF-TCP-PortSharing45
    register: web_frame48

  - name: WinRM IIS Extension || WinRM-IIS-Ext
    ansible.windows.win_feature:
      name: WinRM-IIS-Ext
    register: web_winrm

  - name: reboot instance if required after installing Web-Server feature
    ansible.windows.win_reboot:
    when: web_server.reboot_required or web_common.reboot_required or web_health.reboot_required or web_performance.reboot_required or web_security.reboot_required or web_development.reboot_required or web_mgmt.reboot_required or web_frame35.reboot_required or web_frame48.reboot_required or web_winrm.reboot_required

  - name: ensure temp dir exists
    ansible.windows.win_file:
      path: "c:\\temp"
      state: directory

  - name: ensure tna-startup dir exists
    ansible.windows.win_file:
      path: "c:\\tna-startup"
      state: directory

  - name: copy file-downloader script
    ansible.windows.win_copy:
      src: "./files/file-downloader.ps1"
      dest: "c:\\temp\\file-downloader.ps1"

  - name: copy server-setup script
    ansible.windows.win_copy:
      src: "./files/server-setup.ps1"
      dest: "c:\\temp\\server-setup.ps1"

  - name: copy webserver stop script
    ansible.windows.win_copy:
      src: "./files/stop-webserver.ps1"
      dest: "c:\\tna-startup\\stop-webserver.ps1"

  - name: copy webserver start script
    ansible.windows.win_copy:
      src: "./files/start-webserver.ps1"
      dest: "c:\\tna-startup\\start-webserver.ps1"

  - name: copy startup script
    ansible.windows.win_copy:
      src: "./files/startup.ps1"
      dest: "c:\\tna-startup\\startup.ps1"

  - name: copy logfile push script
    ansible.windows.win_copy:
      src: "./files/push-logfiles.ps1"
      dest: "c:\\tna-startup\\push-logfiles.ps1"

  - name: copy updEnv script
    ansible.windows.win_copy:
      src: "./files/updEnv.ps1"
      dest: "c:\\tna-startup\\updEnv.ps1"

  - name: copy SSH key
    ansible.windows.win_copy:
      src: "../../{{ key_name }}"
      dest: "c:\\tna-startup\\{{ key_name }}"

  - ansible.builtin.debug:
      msg:
        - "====================================================================="
        - "setup for {{ hostvars['localhost']['env'] }} - api tier"
        - "====================================================================="

  - name: run server-setup script
    ansible.windows.win_powershell:
      chdir: "c:\\temp"
      script: |
        ./server-setup.ps1 -environment "{{ hostvars['localhost']['env'] }}" -tier "api" -application "discovery" -keyfile "{{ key_name }}"
    ignore_errors: yes

- name: switch to localhost
  hosts: localhost
  gather_facts: false
  tasks:
  - name: wait for WinRM port
    ansible.builtin.wait_for:
      host: "{{ instance_public_ip }}"
      port: 5986
      delay: 120
      timeout: 600
      sleep: 10
      state: started
    register: port
    tags: [ ami ]

- name: switching hosts
  hosts: winhosts
  gather_facts: no
  connection: winrm
  port: 5986
  tasks:
  - ansible.builtin.debug:
      msg:
        - "====================================================================="
        - "checking setup script has finished"
        - "20 second interval with max duration of 5 minutes"
        - "====================================================================="

  - name: check if ec2 instance is ready
    ansible.builtin.win_stat:
      path: "C:\\setup-status.txt"
    register: setup_status
    until: "setup_status.stat.exists"
    retries: 15
    delay: 20

- name: switch to localhost
  hosts: localhost
  gather_facts: true
  tasks:

  - name: create AMI
    amazon.aws.ec2_ami:
      instance_id: "{{ instance_id }}"
      name: "{{ service }}-app-primer-{{ env }}-{{ ansible_date_time.date }} {{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"
      description: "Discovery Backend server - wincore - ready for deployment"
      region: "{{ region }}"
      state: "present"
      wait: yes
      tags:
        Name: "{{ service }}-app-primer-{{ env }}-{{ ansible_date_time.date }} {{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"
        Service: "{{ service }}"
        Owner: "Digital Services"
        CreatedBy: "ansible"
        CostCentre: 53
        Terraform: false

  - name: terminate instance
    ec2_instance:
      instance_ids: "{{ instance_id }}"
      region: "{{ region }}"
      state: "absent"

  - name: remove security group
    amazon.aws.ec2_group:
      name: "ansible-ami-discovery-app-sg"
      region: "{{ region }}"
      state: "absent"
