---
name: Discovery compile and deploy

on:
  workflow_call:
    inputs:
      deploy-environment:
        type: string
        required: true
      deploy-target:
        type: string
        required: true
    secrets:
      AWS_CODEDEPLOY_ARN:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    env:
      user: "${{ github.actor }}"
      deploy_env: "${{ inputs.deploy-environment }}"
      deploy_target: "${{ inputs.deploy-target }}"
      region: "eu-west-2"
    steps:
      - name: Install AWS CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements-aws-cli.txt'

      - name: Install python dependencies
        run: |
          pip install -r scripts/requirements-aws-cli.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEDEPLOY_ARN }}
          aws-region: "${{ env.region }}"

      - name: Deploy Web to ${{ env.deploy_env }}
        if: ${{ inputs.deploy-target  == 'web' || inputs.deploy-target  == 'web_&_api' }}
        env:
          user: "${{ env.user }}"
          deploy_env: "${{ env.deploy_env }}"
        run: |
          echo deploying for $user...
          aws deploy create-deployment \
            --application-name discovery-frontend \
            --deployment-config-name discovery-frontend \
            --deployment-group-name discovery-frontend-group \
            --s3-location bucket=ds-${{ deploy_env }}-deployment-source,bundleType=zip,key=discovery/builds/TNA.Discovery.web.zip
          aws deploy create-deployment \
            --application-name discovery-frontend-internal \
            --deployment-config-name discovery-frontend-internal \
            --deployment-group-name discovery-frontend-internal-group \
            --s3-location bucket=ds-$deploy_env-deployment-source,bundleType=zip,key=discovery/builds/TNA.Discovery.web.zip

      - name: Deploy API to ${{ env.deploy_env }}
        if: ${{ inputs.deploy-target  == 'api' || inputs.deploy-target  == 'web_&_api' }}
        env:
          user: "${{ env.user }}"
          deploy_env: "${{ env.deploy_env }}"
        run: |
          echo deploying for $user...
          aws deploy create-deployment \
            --application-name discovery-backend \
            --deployment-config-name discovery-backend \
            --deployment-group-name discovery-backend-group \
            --s3-location bucket=ds-$deploy_env-deployment-source,bundleType=zip,key=discovery/builds/TNA.Discovery.api.zip
...
