---
name: Set up Discovery Web AMI

permissions:
  id-token: write
  contents: write

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      environment:
        type: string
        required: true
      ansible_var_file:
        type: string
        required: true
      key_name:
        type: string
        required: true
      region:
        type: string
        required: true
      aws_role_arn:
        type: string
        required: true
      playbook_role_arn:
        type: string
        required: true
      vpc_id:
        type: string
        required: true
      subnet_id:
        type: string
        required: true

jobs:
  web-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.branch }}"

      - name: set ansible var file for dev
        run: |
          echo "ANSIBLE_VAR_FILE=${{ inputs.ansible_var_file }}" >> $GITHUB_ENV
          echo "SSH_KEY_FILE=${{ inputs.key_name }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "${{ inputs.region }}"
          role-to-assume: "${{ inputs.aws_role_arn }}"
          output-credentials: true

      - name: download key file
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://ds-dev-kpf-administration/discovery/${{ inputs.key_name }}
          destination: ./${{ inputs.key_name }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ inputs.region }}

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/discovery-req.txt'
      - run: pip install -r ${{ github.workspace }}/.github/workflows/discovery-req.txt

      - name: install ansible.windows
        run: ansible-galaxy collection install ansible.windows

      - name: run ansible playbook
        env:
          AWS_ROLE_ARN: ${{ inputs.playbook_role_arn }}
          VPC_ID: ${{ inputs.vpc_id }}
          SUBNET_ID: ${{ inputs.subnet_id }}
        run: |
          cur_dir=$(pwd)
          cd $cur_dir/discovery/web-wincore
          export AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }}
          export AWS_SECRET_ACCESS_KEY=${{ steps.creds.outputs.aws-secret-access-key }}
          export AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }}
          export AWS_DEFAULT_REGION="${{ inputs.region }}"
          ansible-playbook \
          --extra-vars "ansible_var_file=${{ inputs.ansible_var_file }} key_name=${{ inputs.key_name }} region=${{ inputs.region }} env=${{ inputs.environment }}" \
          --private-key $cur_dir/${{ inputs.key_name }} \
          discovery-web-wincore-playbook.yml
...
