---
name: Initialise EBS

on:
  workflow_call:
    inputs:
      base_role:
        type: string
        required: true
      playbook_role:
        type: string
        required: true
      region:
        type: string
        required: true
      branch:
        type: string
        required: true
      account:
        type: string
        required: true
      db_type:
        type: string
        required: true
      project_name:
        type: string
        required: true
      function:
        type: string
        required: true
      zone:
        type: string
        required: true
      ebs_size:
        type: string
        required: true
      ebs_type:
        type: string
        required: true
      key_name:
        type: string
        required: true
    secrets:
      vpc_id:
        required: true
      subnet_id_a:
        required: true
      subnet_id_b:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  deploy-ebs:
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.account }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          path: main
          ref: "${{ inputs.branch }}"

      - name: Checkout ds-github-actions
        uses: actions/checkout@v4
        with:
          repository: nationalarchives/ds-github-actions
          path: actions

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "${{ inputs.region }}"
          role-to-assume: "${{ inputs.base_role }}"
          output-credentials: true

      - name: download key file
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://ds-${{ inputs.account }}-kpf-administration/ansible/ansible-build-${{ inputs.account }}-${{ inputs.region }}
          destination: ansible-build-${{ inputs.account }}-${{ inputs.region }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ inputs.region }}

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/base-python-req.txt'
      - run: |
          pip install -r ${{ github.workspace }}/actions/.github/workflows/base-python-req.txt

      - name: run ansible playbook
        env:
          VPC_ID: ${{ secrets.vpc_id }}
          SUBNET_ID_A: ${{ secrets.subnet_id_a }}
          SUBNET_ID_B: ${{ secrets.subnet_id_b }}
        run: |
          cur_dir=$(pwd)
          cd $cur_dir/actions/ansible-playbooks/databases/ebs-preparation
          export AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }}
          export AWS_SECRET_ACCESS_KEY=${{ steps.creds.outputs.aws-secret-access-key }}
          export AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }}
          export AWS_DEFAULT_REGION=${{ inputs.region }}
          ansible-playbook -vvv \
          --extra-vars " \
          db_type='${{ inputs.db_type }}' \
          project_name='${{ inputs.project_name }}' \
          function='${{ inputs.function }}' \
          role_arn='${{ inputs.playbook_role }}' \
          account='${{ inputs.account }}' \
          region='${{ inputs.region }}' \
          zone='${{ inputs.zone }}' \
          ebs_size='${{ inputs.ebs_size }}' \
          ebs_type='${{ inputs.ebs_type }}' \ \
          key_name='${{ inputs.key_name }}'" \
          --private-key $cur_dir/${{ inputs.key_name }} \
          ebs-playbook.yml
...
