---
name: Build Postgres AMI

on:
  workflow_call:
    inputs:
      base_role:
        type: string
        required: true
      playbook_role:
        type: string
        required: true
      region:
        type: string
        required: true
      account:
        type: string
        required: true
      branch:
        type: string
        required: true
      key_name:
        type: string
        required: true
      project_name:
        type: string
        required: true
      function:
        type: string
        required: true
      instance_type:
        type: string
        required: true
      volume_size:
        type: string
        required: true
      asm_key:
        type: string
        required: true
      s3_deployment_bucket:
        type: string
        required: true
      s3_deployment_root:
        type: string
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  create-ami:
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.account }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          path: main
          ref: "${{ inputs.branch }}"

      - name: Checkout ds-github-actions
        uses: actions/checkout@v4
        with:
          repository: nationalarchives/ds-github-actions
          path: actions

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "${{ inputs.region }}"
          role-to-assume: "${{ inputs.base_role }}"
          output-credentials: true

      - name: download key file
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://ds-${{ inputs.account }}-kpf-administration/postgres/${{ inputs.key_name }}
          destination: ${{ inputs.key_name }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ inputs.region }}

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/postgres-ami-build-req.txt'
      - run: |
          pip install -r ${{ github.workspace }}/actions/.github/workflows/postgres-ami-build-req.txt

      - name: run ansible playbook
        env:
          VPC_ID: ${{ secrets.VPC_ID }}
          SUBNET_ID: ${{ secrets.SUBNET_ID }}
        run: |
          cur_dir=$(pwd)
          cd $cur_dir/actions/ansible-playbooks/databases/postgres-base
          export AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }}
          export AWS_SECRET_ACCESS_KEY=${{ steps.creds.outputs.aws-secret-access-key }}
          export AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }}
          export AWS_DEFAULT_REGION=${{ inputs.region }}
          ansible-playbook \
          --extra-vars " \
          project_name='${{ inputs.project_name }}' \
          function='${{ inputs.function }}' \
          key_name='${{ inputs.key_name }}' \
          role_arn='${{ inputs.playbook_role }}' \
          asm_key='${{ inputs.asm_key }}' \
          account='${{ inputs.account }}' \
          region='${{ inputs.region }}' \
          instance_type='${{ inputs.instance_type }}' \
          volume_size='${{ inputs.volume_size }}' \
          asm_key='${{ inputs.asm_key }}' \
          s3_deployment_bucket='${{ inputs.s3_deployment_bucket }}' \
          s3_deployment_root='${{ inputs.s3_deployment_root }}'" \
          --private-key $cur_dir/${{ inputs.key_name }} \
          postgres-base-playbook.yml
...
