---
name: Search Indexer AMI
run-name: Search Indexer AMI for ${{ inputs.account }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      account:
        type: string
        required: true
      region:
        type: string
        required: true
      key_name:
        type: string
        required: true
      branch:
        type: string
        required: true
      base_role:
        type: string
        required: true
      playbook_role:
        type: string
        required: true
      instance_type:
        type: string
        required: true
      volume_size:
        type: string
        required: true
      s3_deployment_bucket:
        type: string
        required: true
      s3_deployment_root:
        type: string
        required: true
    secrets:
      vpc_id:
        required: true
      subnet_id:
        required: true

jobs:
  create-ami:
    runs-on: "ubuntu-22.04"
    environment: ${{ inputs.account }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.inputs.branch }}"

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "${{ inputs.region }}"
          role-to-assume: "${{ inputs.base_role }}"
          output-credentials: true

      - name: download key file
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://ds-${{ inputs.account }}-kpf-administration/discovery/${{ inputs.key_name }}
          destination: ${{ inputs.key_name }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ inputs.region }}

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          #cache-dependency-path: '**/base-wincore-req.txt'
      - run: pip install -r ${{ github.workspace }}/.github/workflows/base-wincore-req.txt

      - name: install ansible.windows
        run: ansible-galaxy collection install ansible.windows

      - name: run ansible playbook
        env:
          VPC_ID: ${{ secrets.VPC_ID }}
          SUBNET_ID: ${{ secrets.SUBNET_ID }}
        run: |
          cur_dir=$(pwd)
          cd $cur_dir/discovery/search-indexer
          export AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }}
          export AWS_SECRET_ACCESS_KEY=${{ steps.creds.outputs.aws-secret-access-key }}
          export AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }}
          export AWS_DEFAULT_REGION=${{ inputs.region }}
          ansible-playbook \
          --extra-vars "key_name='${{ inputs.key_name }}' \
          role_arn='${{ inputs.playbook_role }}' \
          account='${{ inputs.account }}' \
          region='${{ inputs.region }}' \
          instance_type='${{ inputs.instance_type }}' \
          volume_size='${{ inputs.volume_size }}'" \
          --private-key $cur_dir/${{ env.SSH_KEY_FILE }} \
          search-indexer-playbook.yml
