name: Update Web Frontend Image Version

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment for which the version is being updated'
        required: true
        type: choice
        options:
          - develop
          - staging
          - live
      new_version:
        description: 'The new version of the frontend application image'
        required: true
        type: string

jobs:
  update-ssm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "NEW_VERSION=${{ inputs.new_version }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
         
          # Set the Parameter Store name based on environment
          echo "PARAMETER_NAME=/application/web/frontend/docker_image-${{ inputs.environment }}" >> $GITHUB_ENV
         
          # Set the AWS account number based on the selected environment
          if [ "${{ inputs.environment }}" == "develop" ]; then
            echo "AWS_ACCOUNT_ID=846769538626" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "337670467269" ]; then
            echo "AWS_ACCOUNT_ID=STAGING_ACCOUNT_ID" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "968803923593" ]; then
            echo "AWS_ACCOUNT_ID=LIVE_ACCOUNT_ID" >> $GITHUB_ENV
          fi

      - name: Update SSM Parameter Store
        run: |
          NEW_IMAGE_TAG="ghcr.io/nationalarchives/ds-frontend:${{ env.NEW_VERSION }}"
          aws ssm put-parameter --name "${{ env.PARAMETER_NAME }}" --value "$NEW_IMAGE_TAG" --type String --overwrite