---
name: Website WordPress AMI

on:
  workflow_call:
    inputs:
      base_role:
        type: string
        required: true
      playbook_role:
        type: string
        required: true
      region:
        type: string
        required: true
      account:
        type: string
        required: true
      branch:
        type: string
        required: true
      key_name:
        type: string
        required: true
      instance_type:
        type: string
        required: true
      volume_size:
        type: string
        required: true
      s3_deployment_bucket:
        type: string
        required: true
      s3_deployment_root:
        type: string
        required: true
      s3_logfile_bucket:
        type: string
        required: true
      s3_logfile_root:
        type: string
        required: true
      wp_int_siteurl:
        type: string
        required: true
      wp_public_siteurl:
        type: string
        required: true
      wp_editor_siteurl:
        type: string
        required: true
      pod_siteurl:
        type: string
        required: true
      pod_root:
        type: string
        required: true
    secrets:
      vpc_id:
        required: true
      subnet_id:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  create-ami:
    runs-on: "ubuntu-latest"
    environment: "${{ inputs.account }}"

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          path: main
          ref: "${{ inputs.branch }}"

      - name: Checkout ds-github-actions
        uses: actions/checkout@v4
        with:
          repository: nationalarchives/ds-github-actions
          path: actions

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "${{ inputs.region }}"
          role-to-assume: "${{ inputs.base_role }}"
          output-credentials: true

      - name: download key file
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://ds-${{ inputs.account }}-kpf-administration/wp-website/${{ inputs.key_name }}
          destination: ${{ inputs.key_name }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ inputs.region }}

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/website-wp-ami-build-req.txt'
      - run: |
          pip install -r ${{ github.workspace }}/actions/.github/workflows/website-wp-ami-build-req.txt

      - name: run ansible playbook
        run: |
          cur_dir=$(pwd)
          cd $cur_dir/actions/ansible-playbooks/website/wordpress
          export AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }}
          export AWS_SECRET_ACCESS_KEY=${{ steps.creds.outputs.aws-secret-access-key }}
          export AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }}
          export AWS_DEFAULT_REGION=${{ inputs.region }}
          ansible-playbook \
          --extra-vars " \
          key_name='${{ inputs.key_name }}' \
          role_arn='${{ inputs.playbook_role }}' \
          account='${{ inputs.account }}' \
          region='${{ inputs.region }}' \
          instance_type='${{ inputs.instance_type }}' \
          volume_size='${{ inputs.volume_size }}' \
          s3_deployment_bucket='${{ inputs.s3_deployment_bucket }}' \
          s3_deployment_root='${{ inputs.s3_deployment_root }}' \
          s3_logfile_bucket='${{ inputs.s3_logfile_bucket }}' \
          s3_logfile_root='${{ inputs.s3_logfile_root }}' \
          wp_int_siteurl='${{ inputs.wp_int_siteurl }}' \
          wp_public_siteurl='${{ inputs.wp_public_siteurl }}' \
          wp_editor_siteurl='${{ inputs.wp_editor_siteurl }}' \
          pod_siteurl='${{ inputs.pod_siteurl }}' \
          pod_root='${{ inputs.pod_root }}' \
          vpc_id='${{ secrets.vpc_id }}' \
          subnet_id='${{ secrets.subnet_id }}'" \
          --private-key $cur_dir/${{ inputs.key_name }} \
          website-wordpress-playbook.yml
...
